name: Deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.SSH_HOST }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Set Directory Name
        run: echo "DEPLOY_DIR=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_ENV
      - name: Deploy
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /var/www/lookbot/releases &&
          mkdir $DEPLOY_DIR &&
          cd $DEPLOY_DIR &&
          git clone git@github.com:develop-dmitry/look-bot.git . &&
          sudo chown www-data:www-data . -R &&
          sh bin/build-production.sh &&
          sh bin/deploy.sh"
