name: Tests
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Build
        run: sh ./bin/build.sh $UID
      - name: Tests
        run: sh ./bin/test.sh
