name: Tests
on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install require lib
        run: composer install --ignore-platform-reqs
      - name: Tests
        run: sh ./bin/test.sh
