name: Tests
on:
  repository_dispatch:
    types: [ create-pull-request ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Build
        run: sh ./bin/build.sh $UID
      - name: Tests
        run: sh ./bin/test.sh
